# escape=`
FROM mcr.microsoft.com/powershell:latest
#LABEL maintainer=""
#RUN apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
SHELL ["pwsh","-Command"]
ADD Modules /root/.local/share/powershell/Modules/